name: check-diff
description: Check what files were modified
outputs:
  is-modified:
    description: "Are the diffs in current and previous commits"
    value: ${{ steps.diff.outputs.is-modified }}
runs:
  using: "composite"
  steps:
    - run: |
        if git diff HEAD^ HEAD --exit-code "SUBDIR" >/dev/null 2>&1
        then
          echo "No changes found in $SUBDIR"
        else
          echo "Changes found in $SUBDIR"
          echo "::set-output name=is-modified::true"
        fi
      id: diff
      shell: bash
