
version: 2
updates:
- package-ecosystem: pip
  directory: "."
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
    - dependency-name: "panoptoextension"
    - dependency-name: "sagecell"
    - dependency-name: "ggbextension"
    - dependency-name: "scrolldepthextension"
    - dependency-name: "hoverroleextension"
    - dependency-name: "toggleblock"
    - dependency-name: "custom-button"
    - dependency-name: "sphinxcontrib-katex"
