
name: Build sphinx docs and upload with sftp
on:
  push:
jobs:
  Edbook-deploy:
    environment:
      name: staging
      url: https://notendur.hi.is/jlg2/staging/edbook/${{ steps.extract_branch.outputs.branch }}
    name: Edbook-deploy
    runs-on: ubuntu-latest
    timeout-minutes: 30
    defaults:
      run:
        working-directory: hi-cli
    strategy:
      matrix:
        python-version: [3.8]
    env:
      HI_USERNAME: ${{ secrets.HI_FTP_USER }}
      HI_PASSWORD: ${{ secrets.HI_FTP_PASSWORD }}
      DEFAULT_BRANCH: master
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
    - id: python_version
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Extract branch name
    - id: extract_branch
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"

    - name: Install dependencies
    - id: install_dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install

    - name: Build
    - id: build
      run: poetry run hicli build

    - name: Trash remote files
    - id: remote_cleanup
      run: poetry run hicli server --host krafla.rhi.hi.is delete --remote-dir .public_html/staging/edbook/${{ steps.extract_branch.outputs.branch }}

    - name: Copy build dir to remote server
    - id: deploy
      run: poetry run hicli server --host krafla.rhi.hi.is copy --local-dir ../_build --remote-dir .public_html/staging/edbook/${{ steps.extract_branch.outputs.branch }}