
name: Build sphinx docs and upload with sftp

on:
  push:
    branches:
      - docker-integration

jobs:
  SFTP-Deploy-Action:
    name: SFTP-Deploy-Action
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
    steps:
    - uses: actions/checkout@v2.1.0
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Make build
      run: make html && ls _build

    - name: upload
      run: python .deployment/main.py --user ${{ secrets.HI_FTP_USER }} --password ${{ secrets.HI_FTP_PASSWORD }} --dir "../_build/html"
