name: Deploy
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.4.6
        with:
          usedocker: true
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "undirbuningur-stae" #Must be unique in Heroku
          heroku_email: "levito@gmail.com"