
name: Build sphinx docs and upload with sftp

on:
  push:
    branches:
      - docker-integration

jobs:
  SFTP-Deploy-Action:
    name: SFTP-Deploy-Action
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: hi-cli
    strategy:
      matrix:
        python-version: [3.8]
    steps:
    - uses: actions/checkout@v2.1.0
      env:
        HI_USERNAME: ${{ secrets.HI_FTP_USER }}
        HI_PASSWORD: ${{ secrets.HI_FTP_PASSWORD }}
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install

    - name: Build
      run: poetry run hicli build

    - name: List remote files
      run: poetry run hicli server list --remote-dir .public-html

    - name: Trash remote files
      run: poetry run hicli server delete .public_html/edbook

    - name: Copy build dir to remote server
      run: poetry run hicli server copy ../_build .public_html